### PR TITLE
Test python_daemon without the need of arduino

### PR DESCRIPTION
**Pull request by edjaguilar**
Simulate arduino code from python script connected via pty interface
A pty device pair can be created using socat:

> socat -d -d PTY,raw,echo=0 PTY,raw,echo=0
> 2020/03/30 13:25:41 socat[12517] N PTY is /dev/pts/4
> 2020/03/30 13:25:41 socat[12517] N PTY is /dev/pts/5
> 2020/03/30 13:25:41 socat[12517] N starting data transfer loop with FDs [5,5] and [7,7]

Add the path to each device as argument to both daemon and dummyPrint.py

### CODE REVIEW

**Comment by frankvanbever** [comment]
Could you maybe add a shell script that does the pty set-up automatically? That way it's documented in the repo

**Comment by RenaultR42** [comment]
> Could you maybe add a shell script that does the pty set-up automatically? That way it's documented in the repo

Hum, from my point of view it is better to add this information + setup in Docker file or system integration system. But definitively, it should be documented somewhere.

**Comment by edjaguilar** [comment]
Maybe just a README.md ? I can maybe add script with socat with known names, which would be clearer maybe

**Comment by edjaguilar** [comment]
I added some exception handling to avoid too many errors when finishing the script that launches both daemon and dummyPrint (I added a trap that kills all subprocesses to make sure to end all python threads)

**Review by TomBruyneel — APPROVED** [review]

**Pull request merged**
